package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AssessmentType generated by hbm2java
 */
@Entity
@Table(name = "assessment_type", catalog = "hiring")
public class AssessmentType implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set candidateHasAssessments = new HashSet(0);

	public AssessmentType() {
	}

	public AssessmentType(int id) {
		this.id = id;
	}

	public AssessmentType(int id, String name, String description, Set candidateHasAssessments) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.candidateHasAssessments = candidateHasAssessments;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assessmentType")
	public Set getCandidateHasAssessments() {
		return this.candidateHasAssessments;
	}

	public void setCandidateHasAssessments(Set candidateHasAssessments) {
		this.candidateHasAssessments = candidateHasAssessments;
	}

}
