package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CandidateHasLevelInSkillId generated by hbm2java
 */
@Embeddable
public class CandidateHasLevelInSkillId implements java.io.Serializable {

	private int candidateIdcandidate;
	private int levelIdlevel;
	private int skillIdskill;

	public CandidateHasLevelInSkillId() {
	}

	public CandidateHasLevelInSkillId(int candidateIdcandidate, int levelIdlevel, int skillIdskill) {
		this.candidateIdcandidate = candidateIdcandidate;
		this.levelIdlevel = levelIdlevel;
		this.skillIdskill = skillIdskill;
	}

	@Column(name = "candidate_idcandidate", nullable = false)
	public int getCandidateIdcandidate() {
		return this.candidateIdcandidate;
	}

	public void setCandidateIdcandidate(int candidateIdcandidate) {
		this.candidateIdcandidate = candidateIdcandidate;
	}

	@Column(name = "level_idlevel", nullable = false)
	public int getLevelIdlevel() {
		return this.levelIdlevel;
	}

	public void setLevelIdlevel(int levelIdlevel) {
		this.levelIdlevel = levelIdlevel;
	}

	@Column(name = "skill_idskill", nullable = false)
	public int getSkillIdskill() {
		return this.skillIdskill;
	}

	public void setSkillIdskill(int skillIdskill) {
		this.skillIdskill = skillIdskill;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CandidateHasLevelInSkillId))
			return false;
		CandidateHasLevelInSkillId castOther = (CandidateHasLevelInSkillId) other;

		return (this.getCandidateIdcandidate() == castOther.getCandidateIdcandidate())
				&& (this.getLevelIdlevel() == castOther.getLevelIdlevel())
				&& (this.getSkillIdskill() == castOther.getSkillIdskill());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCandidateIdcandidate();
		result = 37 * result + this.getLevelIdlevel();
		result = 37 * result + this.getSkillIdskill();
		return result;
	}

}
