package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CandidateHasAssessmentId generated by hbm2java
 */
@Embeddable
public class CandidateHasAssessmentId implements java.io.Serializable {

	private int candidateIdcandidate;
	private int assessmentIdassessment;
	private int assessmentTypeId;

	public CandidateHasAssessmentId() {
	}

	public CandidateHasAssessmentId(int candidateIdcandidate, int assessmentIdassessment, int assessmentTypeId) {
		this.candidateIdcandidate = candidateIdcandidate;
		this.assessmentIdassessment = assessmentIdassessment;
		this.assessmentTypeId = assessmentTypeId;
	}

	@Column(name = "candidate_idcandidate", nullable = false)
	public int getCandidateIdcandidate() {
		return this.candidateIdcandidate;
	}

	public void setCandidateIdcandidate(int candidateIdcandidate) {
		this.candidateIdcandidate = candidateIdcandidate;
	}

	@Column(name = "assessment_idassessment", nullable = false)
	public int getAssessmentIdassessment() {
		return this.assessmentIdassessment;
	}

	public void setAssessmentIdassessment(int assessmentIdassessment) {
		this.assessmentIdassessment = assessmentIdassessment;
	}

	@Column(name = "assessment_type_id", nullable = false)
	public int getAssessmentTypeId() {
		return this.assessmentTypeId;
	}

	public void setAssessmentTypeId(int assessmentTypeId) {
		this.assessmentTypeId = assessmentTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CandidateHasAssessmentId))
			return false;
		CandidateHasAssessmentId castOther = (CandidateHasAssessmentId) other;

		return (this.getCandidateIdcandidate() == castOther.getCandidateIdcandidate())
				&& (this.getAssessmentIdassessment() == castOther.getAssessmentIdassessment())
				&& (this.getAssessmentTypeId() == castOther.getAssessmentTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCandidateIdcandidate();
		result = 37 * result + this.getAssessmentIdassessment();
		result = 37 * result + this.getAssessmentTypeId();
		return result;
	}

}
