package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CandidateHasLevelInSkill generated by hbm2java
 */
@Entity
@Table(name = "candidate_has_level_in_skill", catalog = "hiring")
public class CandidateHasLevelInSkill implements java.io.Serializable {

	private CandidateHasLevelInSkillId id;
	private Candidate candidate;
	private Level level;
	private Skill skill;

	public CandidateHasLevelInSkill() {
	}

	public CandidateHasLevelInSkill(CandidateHasLevelInSkillId id, Candidate candidate, Level level, Skill skill) {
		this.id = id;
		this.candidate = candidate;
		this.level = level;
		this.skill = skill;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "candidateIdcandidate", column = @Column(name = "candidate_idcandidate", nullable = false)),
			@AttributeOverride(name = "levelIdlevel", column = @Column(name = "level_idlevel", nullable = false)),
			@AttributeOverride(name = "skillIdskill", column = @Column(name = "skill_idskill", nullable = false)) })
	public CandidateHasLevelInSkillId getId() {
		return this.id;
	}

	public void setId(CandidateHasLevelInSkillId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_idcandidate", nullable = false, insertable = false, updatable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "level_idlevel", nullable = false, insertable = false, updatable = false)
	public Level getLevel() {
		return this.level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "skill_idskill", nullable = false, insertable = false, updatable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

}
