package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "hiring")
public class Company implements java.io.Serializable {

	private int idcompany;
	private String name;
	private String isSubcontractor;
	private Set candidates = new HashSet(0);
	private Set experiences = new HashSet(0);

	public Company() {
	}

	public Company(int idcompany) {
		this.idcompany = idcompany;
	}

	public Company(int idcompany, String name, String isSubcontractor, Set candidates, Set experiences) {
		this.idcompany = idcompany;
		this.name = name;
		this.isSubcontractor = isSubcontractor;
		this.candidates = candidates;
		this.experiences = experiences;
	}

	@Id

	@Column(name = "idcompany", unique = true, nullable = false)
	public int getIdcompany() {
		return this.idcompany;
	}

	public void setIdcompany(int idcompany) {
		this.idcompany = idcompany;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_subcontractor", length = 45)
	public String getIsSubcontractor() {
		return this.isSubcontractor;
	}

	public void setIsSubcontractor(String isSubcontractor) {
		this.isSubcontractor = isSubcontractor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set candidates) {
		this.candidates = candidates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set getExperiences() {
		return this.experiences;
	}

	public void setExperiences(Set experiences) {
		this.experiences = experiences;
	}

}
