package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExperienceId generated by hbm2java
 */
@Embeddable
public class ExperienceId implements java.io.Serializable {

	private int idexperience;
	private int candidateIdcandidate;
	private int employerIdemployer;

	public ExperienceId() {
	}

	public ExperienceId(int idexperience, int candidateIdcandidate, int employerIdemployer) {
		this.idexperience = idexperience;
		this.candidateIdcandidate = candidateIdcandidate;
		this.employerIdemployer = employerIdemployer;
	}

	@Column(name = "idexperience", nullable = false)
	public int getIdexperience() {
		return this.idexperience;
	}

	public void setIdexperience(int idexperience) {
		this.idexperience = idexperience;
	}

	@Column(name = "candidate_idcandidate", nullable = false)
	public int getCandidateIdcandidate() {
		return this.candidateIdcandidate;
	}

	public void setCandidateIdcandidate(int candidateIdcandidate) {
		this.candidateIdcandidate = candidateIdcandidate;
	}

	@Column(name = "employer_idemployer", nullable = false)
	public int getEmployerIdemployer() {
		return this.employerIdemployer;
	}

	public void setEmployerIdemployer(int employerIdemployer) {
		this.employerIdemployer = employerIdemployer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExperienceId))
			return false;
		ExperienceId castOther = (ExperienceId) other;

		return (this.getIdexperience() == castOther.getIdexperience())
				&& (this.getCandidateIdcandidate() == castOther.getCandidateIdcandidate())
				&& (this.getEmployerIdemployer() == castOther.getEmployerIdemployer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdexperience();
		result = 37 * result + this.getCandidateIdcandidate();
		result = 37 * result + this.getEmployerIdemployer();
		return result;
	}

}
