package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Interview generated by hbm2java
 */
@Entity
@Table(name = "interview", catalog = "hiring")
public class Interview implements java.io.Serializable {

	private int idinterview;
	private Candidate candidate;
	private User user;
	private Date date;
	private String detail;

	public Interview() {
	}

	public Interview(int idinterview, Candidate candidate, User user) {
		this.idinterview = idinterview;
		this.candidate = candidate;
		this.user = user;
	}

	public Interview(int idinterview, Candidate candidate, User user, Date date, String detail) {
		this.idinterview = idinterview;
		this.candidate = candidate;
		this.user = user;
		this.date = date;
		this.detail = detail;
	}

	@Id

	@Column(name = "idinterview", unique = true, nullable = false)
	public int getIdinterview() {
		return this.idinterview;
	}

	public void setIdinterview(int idinterview) {
		this.idinterview = idinterview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_idcandidate", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_iduser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "detail")
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
