package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Level generated by hbm2java
 */
@Entity
@Table(name = "level", catalog = "hiring")
public class Level implements java.io.Serializable {

	private int idlevel;
	private String name;
	private Set questions = new HashSet(0);
	private Set candidateHasLevelInSkills = new HashSet(0);

	public Level() {
	}

	public Level(int idlevel) {
		this.idlevel = idlevel;
	}

	public Level(int idlevel, String name, Set questions, Set candidateHasLevelInSkills) {
		this.idlevel = idlevel;
		this.name = name;
		this.questions = questions;
		this.candidateHasLevelInSkills = candidateHasLevelInSkills;
	}

	@Id

	@Column(name = "idlevel", unique = true, nullable = false)
	public int getIdlevel() {
		return this.idlevel;
	}

	public void setIdlevel(int idlevel) {
		this.idlevel = idlevel;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "level")
	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "level")
	public Set getCandidateHasLevelInSkills() {
		return this.candidateHasLevelInSkills;
	}

	public void setCandidateHasLevelInSkills(Set candidateHasLevelInSkills) {
		this.candidateHasLevelInSkills = candidateHasLevelInSkills;
	}

}
