package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "hiring")
public class Person implements java.io.Serializable {

	private int idpersonn;
	private String gender;
	private String firstName;
	private String lastName;
	private String email;
	private Set candidates = new HashSet(0);
	private Set users = new HashSet(0);

	public Person() {
	}

	public Person(int idpersonn) {
		this.idpersonn = idpersonn;
	}

	public Person(int idpersonn, String gender, String firstName, String lastName, String email, Set candidates,
			Set users) {
		this.idpersonn = idpersonn;
		this.gender = gender;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.candidates = candidates;
		this.users = users;
	}

	@Id

	@Column(name = "idpersonn", unique = true, nullable = false)
	public int getIdpersonn() {
		return this.idpersonn;
	}

	public void setIdpersonn(int idpersonn) {
		this.idpersonn = idpersonn;
	}

	@Column(name = "gender", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 65)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set candidates) {
		this.candidates = candidates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
