package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Preference generated by hbm2java
 */
@Entity
@Table(name = "preference", catalog = "hiring")
public class Preference implements java.io.Serializable {

	private int idpreference;
	private Candidate candidate;
	private String value;

	public Preference() {
	}

	public Preference(int idpreference, Candidate candidate) {
		this.idpreference = idpreference;
		this.candidate = candidate;
	}

	public Preference(int idpreference, Candidate candidate, String value) {
		this.idpreference = idpreference;
		this.candidate = candidate;
		this.value = value;
	}

	@Id

	@Column(name = "idpreference", unique = true, nullable = false)
	public int getIdpreference() {
		return this.idpreference;
	}

	public void setIdpreference(int idpreference) {
		this.idpreference = idpreference;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_idcandidate", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
