package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionExpectedAnswer generated by hbm2java
 */
@Entity
@Table(name = "question_expected_answer", catalog = "hiring")
public class QuestionExpectedAnswer implements java.io.Serializable {

	private int idquestionAnswer;
	private Question question;
	private String value;

	public QuestionExpectedAnswer() {
	}

	public QuestionExpectedAnswer(int idquestionAnswer, Question question) {
		this.idquestionAnswer = idquestionAnswer;
		this.question = question;
	}

	public QuestionExpectedAnswer(int idquestionAnswer, Question question, String value) {
		this.idquestionAnswer = idquestionAnswer;
		this.question = question;
		this.value = value;
	}

	@Id

	@Column(name = "idquestion_answer", unique = true, nullable = false)
	public int getIdquestionAnswer() {
		return this.idquestionAnswer;
	}

	public void setIdquestionAnswer(int idquestionAnswer) {
		this.idquestionAnswer = idquestionAnswer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_idquestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
