package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionType generated by hbm2java
 */
@Entity
@Table(name = "question_type", catalog = "hiring")
public class QuestionType implements java.io.Serializable {

	private int idquestionType;
	private String name;
	private Set questions = new HashSet(0);

	public QuestionType() {
	}

	public QuestionType(int idquestionType) {
		this.idquestionType = idquestionType;
	}

	public QuestionType(int idquestionType, String name, Set questions) {
		this.idquestionType = idquestionType;
		this.name = name;
		this.questions = questions;
	}

	@Id

	@Column(name = "idquestion_type", unique = true, nullable = false)
	public int getIdquestionType() {
		return this.idquestionType;
	}

	public void setIdquestionType(int idquestionType) {
		this.idquestionType = idquestionType;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionType")
	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}

}
