package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionProposal generated by hbm2java
 */
@Entity
@Table(name = "question_proposal", catalog = "hiring")
public class QuestionProposal implements java.io.Serializable {

	private int idquestionProposal;
	private Question question;
	private String value;

	public QuestionProposal() {
	}

	public QuestionProposal(int idquestionProposal, Question question) {
		this.idquestionProposal = idquestionProposal;
		this.question = question;
	}

	public QuestionProposal(int idquestionProposal, Question question, String value) {
		this.idquestionProposal = idquestionProposal;
		this.question = question;
		this.value = value;
	}

	@Id

	@Column(name = "idquestion_proposal", unique = true, nullable = false)
	public int getIdquestionProposal() {
		return this.idquestionProposal;
	}

	public void setIdquestionProposal(int idquestionProposal) {
		this.idquestionProposal = idquestionProposal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_idquestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
