package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school", catalog = "hiring")
public class School implements java.io.Serializable {

	private int idschool;
	private String name;
	private Set trainings = new HashSet(0);

	public School() {
	}

	public School(int idschool) {
		this.idschool = idschool;
	}

	public School(int idschool, String name, Set trainings) {
		this.idschool = idschool;
		this.name = name;
		this.trainings = trainings;
	}

	@Id

	@Column(name = "idschool", unique = true, nullable = false)
	public int getIdschool() {
		return this.idschool;
	}

	public void setIdschool(int idschool) {
		this.idschool = idschool;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set getTrainings() {
		return this.trainings;
	}

	public void setTrainings(Set trainings) {
		this.trainings = trainings;
	}

}
