package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name = "sector", catalog = "hiring")
public class Sector implements java.io.Serializable {

	private int idsector;
	private String name;
	private Set candidates = new HashSet(0);

	public Sector() {
	}

	public Sector(int idsector) {
		this.idsector = idsector;
	}

	public Sector(int idsector, String name, Set candidates) {
		this.idsector = idsector;
		this.name = name;
		this.candidates = candidates;
	}

	@Id

	@Column(name = "idsector", unique = true, nullable = false)
	public int getIdsector() {
		return this.idsector;
	}

	public void setIdsector(int idsector) {
		this.idsector = idsector;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "candidate_has_sector", catalog = "hiring", joinColumns = {
			@JoinColumn(name = "sector_idsector", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "candidate_idcandidate", nullable = false, updatable = false) })
	public Set getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set candidates) {
		this.candidates = candidates;
	}

}
