package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "skill", catalog = "hiring")
public class Skill implements java.io.Serializable {

	private int idskill;
	private String name;
	private Set candidateHasLevelInSkills = new HashSet(0);
	private Set questions = new HashSet(0);

	public Skill() {
	}

	public Skill(int idskill) {
		this.idskill = idskill;
	}

	public Skill(int idskill, String name, Set candidateHasLevelInSkills, Set questions) {
		this.idskill = idskill;
		this.name = name;
		this.candidateHasLevelInSkills = candidateHasLevelInSkills;
		this.questions = questions;
	}

	@Id

	@Column(name = "idskill", unique = true, nullable = false)
	public int getIdskill() {
		return this.idskill;
	}

	public void setIdskill(int idskill) {
		this.idskill = idskill;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
	public Set getCandidateHasLevelInSkills() {
		return this.candidateHasLevelInSkills;
	}

	public void setCandidateHasLevelInSkills(Set candidateHasLevelInSkills) {
		this.candidateHasLevelInSkills = candidateHasLevelInSkills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}

}
