package com.hiring.entities;
// Generated 10 oct. 2018 14:34:30 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Training generated by hbm2java
 */
@Entity
@Table(name = "training", catalog = "hiring")
public class Training implements java.io.Serializable {

	private TrainingId id;
	private Candidate candidate;
	private School school;
	private String name;
	private String startDate;
	private String endDate;

	public Training() {
	}

	public Training(TrainingId id, Candidate candidate, School school) {
		this.id = id;
		this.candidate = candidate;
		this.school = school;
	}

	public Training(TrainingId id, Candidate candidate, School school, String name, String startDate, String endDate) {
		this.id = id;
		this.candidate = candidate;
		this.school = school;
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idtraining", column = @Column(name = "idtraining", nullable = false)),
			@AttributeOverride(name = "candidateIdcandidate", column = @Column(name = "candidate_idcandidate", nullable = false)),
			@AttributeOverride(name = "schoolIdschool", column = @Column(name = "school_idschool", nullable = false)) })
	public TrainingId getId() {
		return this.id;
	}

	public void setId(TrainingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_idcandidate", nullable = false, insertable = false, updatable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_idschool", nullable = false, insertable = false, updatable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "start_date", length = 45)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

}
